import React, { useEffect, useState } from 'react'
import { supabase } from '../supabaseClient'

// PayPal payment link is generated via PayPal.me or PayPal invoice API
// Free option: PayPal.me link (no API needed)
// Format: https://paypal.me/YourPayPalUsername/Amount

const PAYPAL_USERNAME = 'UniEDDPayments' // ← Change this to your PayPal.me username

export default function PaymentsAdmin({ profile }) {
  const [payments,   setPayments]   = useState([])
  const [loading,    setLoading]    = useState(true)
  const [filter,     setFilter]     = useState('all')
  const [ok,         setOk]         = useState('')
  const [err,        setErr]        = useState('')
  const [generating, setGenerating] = useState(null)

  useEffect(() => { load() }, [])

  async function load() {
    setLoading(true)
    const { data } = await supabase
      .from('payments')
      .select('*')
      .order('created_at', { ascending: false })
    setPayments(data || [])
    setLoading(false)
  }

  async function generatePayPalLink(inv) {
    setGenerating(inv.id)
    setErr(''); setOk('')

    // Generate PayPal.me link (free, no API needed)
    // Format: https://paypal.me/username/amount/currency
    const amount   = inv.amount || 0
    const currency = 'USD' // PayPal.me uses USD by default
    // Convert INR to USD approx (or use USD directly)
    const amountUSD = (amount / 83).toFixed(2) // approx INR→USD
    const paypalLink = `https://paypal.me/${PAYPAL_USERNAME}/${amountUSD}`

    const { error } = await supabase
      .from('payments')
      .update({
        payment_link: paypalLink,
        status:       'pending',
        notes:        (inv.notes || '') + `\nPayPal link generated by ${profile.full_name} on ${new Date().toLocaleDateString('en-IN')}`,
      })
      .eq('id', inv.id)

    if (error) setErr(error.message)
    else setOk(`✓ PayPal link generated for ${inv.student_name}! They can now pay ₹${amount} (≈$${amountUSD}).`)

    setGenerating(null)
    load()
    setTimeout(() => setOk(''), 5000)
  }

  async function markPaid(id, studentName) {
    await supabase.from('payments').update({
      status:    'paid',
      paid_date: new Date().toISOString().slice(0,10),
    }).eq('id', id)
    setOk(`✓ ${studentName} marked as paid!`)
    load()
    setTimeout(() => setOk(''), 3000)
  }

  async function markOverdue(id) {
    await supabase.from('payments').update({ status: 'overdue' }).eq('id', id)
    load()
  }

  const filtered = filter === 'all' ? payments : payments.filter(p => {
    if (filter === 'requested') return p.notes?.includes('PAYMENT LINK REQUESTED') && !p.payment_link
    return p.status === filter
  })

  const totalRevenue  = payments.filter(p=>p.status==='paid').reduce((a,p)=>a+(p.amount||0),0)
  const totalPending  = payments.filter(p=>p.status==='pending').reduce((a,p)=>a+(p.amount||0),0)
  const requested     = payments.filter(p=>p.notes?.includes('PAYMENT LINK REQUESTED') && !p.payment_link)

  const STATUS_COLOR = {
    paid:    { bg:'rgba(16,185,129,0.15)',  color:'#10b981' },
    pending: { bg:'rgba(244,163,53,0.15)',  color:'#f4a335' },
    overdue: { bg:'rgba(239,68,68,0.15)',   color:'#f87171' },
  }

  return (
    <div id="uniedd-payments" style={{ marginTop:'14px' }}>
      <div style={{ background:'rgba(255,255,255,0.04)', border:'0.5px solid rgba(255,255,255,0.07)', borderRadius:'14px', padding:'1rem 1.1rem' }}>

        {/* Header */}
        <div style={{ fontSize:'13px', fontWeight:700, color:'rgba(255,255,255,0.7)', marginBottom:'14px', paddingBottom:'8px', borderBottom:'0.5px solid rgba(255,255,255,0.06)' }}>
          💳 Payments & Invoices
        </div>

        {/* Stats */}
        <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))', gap:'10px', marginBottom:'14px' }}>
          {[
            { label:'Total Revenue',  value:`₹${totalRevenue.toLocaleString('en-IN')}`,  color:'#10b981', bg:'rgba(16,185,129,0.1)'  },
            { label:'Pending Amount', value:`₹${totalPending.toLocaleString('en-IN')}`,  color:'#f4a335', bg:'rgba(244,163,53,0.1)'  },
            { label:'Link Requests',  value:requested.length,                             color:'#a78bfa', bg:'rgba(139,92,246,0.1)'  },
            { label:'Total Invoices', value:payments.length,                              color:'#5aabff', bg:'rgba(30,144,255,0.1)'  },
          ].map(s => (
            <div key={s.label} style={{ background:s.bg, borderRadius:'12px', padding:'12px', border:`0.5px solid ${s.color}33` }}>
              <div style={{ fontSize:'10px', fontWeight:700, color:'rgba(255,255,255,0.4)', letterSpacing:'0.08em', textTransform:'uppercase', marginBottom:'4px' }}>{s.label}</div>
              <div style={{ fontSize:'20px', fontWeight:800, color:s.color }}>{s.value}</div>
            </div>
          ))}
        </div>

        {/* PayPal config note */}
        <div style={{ marginBottom:'12px', padding:'10px 14px', background:'rgba(30,144,255,0.07)', border:'0.5px solid rgba(30,144,255,0.2)', borderRadius:'10px', fontSize:'12px', color:'rgba(255,255,255,0.45)', lineHeight:1.6 }}>
          <strong style={{ color:'#5aabff' }}>PayPal Setup:</strong> Links use PayPal.me/<strong style={{ color:'#e87c1e' }}>{PAYPAL_USERNAME}</strong>.
          To change this, update <code style={{ color:'#e87c1e' }}>PAYPAL_USERNAME</code> in <code>PaymentsAdmin.js</code>.
          Create your PayPal.me at <a href="https://paypal.me" target="_blank" rel="noreferrer" style={{ color:'#5aabff' }}>paypal.me</a>
        </div>

        {/* Filter tabs */}
        <div style={{ display:'flex', gap:'6px', marginBottom:'12px', flexWrap:'wrap' }}>
          {[
            { id:'all',       label:'All' },
            { id:'requested', label:`🔔 Requests (${requested.length})` },
            { id:'pending',   label:'Pending'  },
            { id:'paid',      label:'Paid'     },
            { id:'overdue',   label:'Overdue'  },
          ].map(f => (
            <button key={f.id} onClick={() => setFilter(f.id)} style={{
              fontSize:'12px', fontWeight:600, padding:'6px 14px', borderRadius:'20px', border:'none', cursor:'pointer',
              background: filter===f.id ? '#1e90ff' : 'rgba(255,255,255,0.07)',
              color:      filter===f.id ? '#fff'    : 'rgba(255,255,255,0.45)',
            }}>{f.label}</button>
          ))}
        </div>

        {ok  && <div style={{ marginBottom:'10px', padding:'8px 12px', background:'rgba(16,185,129,0.1)', border:'0.5px solid rgba(16,185,129,0.3)', borderRadius:'8px', fontSize:'13px', color:'#34d399' }}>{ok}</div>}
        {err && <div style={{ marginBottom:'10px', padding:'8px 12px', background:'rgba(220,60,60,0.1)', border:'0.5px solid rgba(220,60,60,0.3)', borderRadius:'8px', fontSize:'13px', color:'#f09595' }}>{err}</div>}

        {loading ? (
          <div style={{ textAlign:'center', padding:'2rem', color:'rgba(255,255,255,0.2)', fontSize:'13px' }}>Loading...</div>
        ) : filtered.length === 0 ? (
          <div style={{ textAlign:'center', padding:'2rem', color:'rgba(255,255,255,0.2)', fontSize:'13px' }}>
            {filter === 'requested' ? 'No payment link requests from sales team.' : 'No invoices found.'}
          </div>
        ) : (
          <div style={{ display:'grid', gap:'8px' }}>
            {filtered.map(inv => {
              const sc         = STATUS_COLOR[inv.status] || STATUS_COLOR.pending
              const isRequested= inv.notes?.includes('PAYMENT LINK REQUESTED') && !inv.payment_link
              const isGenerating = generating === inv.id
              return (
                <div key={inv.id} style={{
                  background: isRequested ? 'rgba(139,92,246,0.07)' : 'rgba(255,255,255,0.03)',
                  border: isRequested ? '0.5px solid rgba(139,92,246,0.3)' : '0.5px solid rgba(255,255,255,0.06)',
                  borderRadius:'12px', padding:'14px',
                }}>
                  <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', flexWrap:'wrap', gap:'8px', marginBottom:'8px' }}>
                    <div>
                      <div style={{ display:'flex', alignItems:'center', gap:'8px', flexWrap:'wrap' }}>
                        <span style={{ fontSize:'13px', fontWeight:700, color:'#e87c1e' }}>{inv.invoice_no || 'No #'}</span>
                        <span style={{ fontSize:'10px', fontWeight:700, padding:'2px 8px', borderRadius:'10px', background:sc.bg, color:sc.color, textTransform:'capitalize' }}>{inv.status}</span>
                        {isRequested && <span style={{ fontSize:'10px', fontWeight:700, padding:'2px 8px', borderRadius:'10px', background:'rgba(139,92,246,0.2)', color:'#a78bfa' }}>🔔 Link Requested</span>}
                      </div>
                      <div style={{ fontSize:'14px', fontWeight:600, color:'rgba(255,255,255,0.85)', marginTop:'4px' }}>{inv.student_name}</div>
                      {inv.student_email && <div style={{ fontSize:'11px', color:'rgba(255,255,255,0.3)' }}>{inv.student_email}</div>}
                    </div>
                    <div style={{ textAlign:'right' }}>
                      <div style={{ fontSize:'20px', fontWeight:800, color:'#10b981' }}>₹{(inv.amount||0).toLocaleString('en-IN')}</div>
                      {inv.discount_pct > 0 && <div style={{ fontSize:'11px', color:'rgba(255,255,255,0.3)' }}>{inv.discount_pct}% discount applied</div>}
                    </div>
                  </div>

                  {inv.description && (
                    <div style={{ fontSize:'12px', color:'rgba(255,255,255,0.4)', marginBottom:'8px' }}>{inv.description}</div>
                  )}

                  {inv.notes && !inv.notes.includes('PAYMENT LINK REQUESTED') && (
                    <div style={{ fontSize:'11px', color:'rgba(255,255,255,0.25)', marginBottom:'8px', fontStyle:'italic' }}>{inv.notes}</div>
                  )}

                  <div style={{ fontSize:'11px', color:'rgba(255,255,255,0.25)', marginBottom:'10px' }}>
                    Created: {new Date(inv.created_at).toLocaleDateString('en-IN')}
                    {inv.generated_by && ` · By ${inv.generated_by}`}
                    {inv.paid_date && ` · Paid: ${inv.paid_date}`}
                  </div>

                  {/* Actions */}
                  <div style={{ display:'flex', gap:'8px', flexWrap:'wrap' }}>
                    {inv.payment_link ? (
                      <a href={inv.payment_link} target="_blank" rel="noreferrer" style={{ fontSize:'12px', fontWeight:700, padding:'6px 14px', borderRadius:'8px', background:'rgba(16,185,129,0.15)', color:'#10b981', border:'0.5px solid rgba(16,185,129,0.3)' }}>
                        💳 PayPal Link ↗
                      </a>
                    ) : (
                      <button
                        onClick={() => generatePayPalLink(inv)}
                        disabled={isGenerating}
                        style={{ fontSize:'12px', fontWeight:700, padding:'6px 14px', borderRadius:'8px', background: isRequested ? '#8b5cf6' : 'rgba(139,92,246,0.15)', color: isRequested ? '#fff' : '#a78bfa', border:'0.5px solid rgba(139,92,246,0.3)', cursor:'pointer', opacity:isGenerating?0.6:1 }}>
                        {isGenerating ? 'Generating...' : '🔗 Generate PayPal Link'}
                      </button>
                    )}
                    {inv.status !== 'paid' && (
                      <button onClick={() => markPaid(inv.id, inv.student_name)} style={{ fontSize:'12px', fontWeight:700, padding:'6px 14px', borderRadius:'8px', background:'rgba(16,185,129,0.15)', color:'#10b981', border:'0.5px solid rgba(16,185,129,0.3)', cursor:'pointer' }}>
                        ✓ Mark Paid
                      </button>
                    )}
                    {inv.status === 'pending' && (
                      <button onClick={() => markOverdue(inv.id)} style={{ fontSize:'12px', fontWeight:700, padding:'6px 14px', borderRadius:'8px', background:'rgba(239,68,68,0.1)', color:'#f87171', border:'0.5px solid rgba(239,68,68,0.2)', cursor:'pointer' }}>
                        Mark Overdue
                      </button>
                    )}
                    {inv.payment_link && (
                      <button onClick={() => {navigator.clipboard.writeText(inv.payment_link); setOk('Link copied!')}} style={{ fontSize:'12px', fontWeight:700, padding:'6px 14px', borderRadius:'8px', background:'rgba(255,255,255,0.07)', color:'rgba(255,255,255,0.5)', border:'0.5px solid rgba(255,255,255,0.1)', cursor:'pointer' }}>
                        📋 Copy Link
                      </button>
                    )}
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </div>
    </div>
  )
}
